### ISSUE TITLE
Allow configuration for use with Github/CircleCI Enterprise

### ISSUE THREAD

**Issue by michael-yx-wu** [cliffrowley/atom-circle-ci#26]
Currently plugin only works for projects on `github.com`. It'd be really cool if the URLs are more configurable to effectively allow for use with enterprise versions of these services.

**Comment by cliffrowley** [comment]
Unfortunately I am no longer using Circle CI so my support for this plugin is limited to contributions.  I am happy to add contributors, should you be willing to jump in :-)

**Comment by cliffrowley** [comment]
@michael-yx-wu what are you using now, out of interest?  I've recently been looking at SpaceEmacs to see what the fuss is about.

**Comment by michael-yx-wu** [comment]
I'm a front end dev these days so I've actually really enjoyed using vscode. Great out of the box typescript support and is incredibly fast compared to Atom. The performance difference was what made me finally convert.

**Comment by cliffrowley** [comment]
Interesting, and makes perfect sense.  I've used VSCode for Unity development and it's pretty awesome actually.

I'll leave this issue open because people do still use this plugin, and hopefully someone will pick it up and do what needs to be done to bring it up to speed.  Or it'll die a death, I don't know - I just don't have time to work on it myself..
